site_name: Brown Lab Documentation
site_url: https://brown-and-briganti.github.io/bel-docs/
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Lab:
    - Managing your files with GitHub: Lab Protocols/github-guide.md
    - In-House Scripts: Lab Protocols/lab-scripts.md
  - ARC:
    - Managing shared software: ARC/Managing Shared Software/installing-gromacs-arc.md
  - Python Fundamentals:
    - Python Fundamentals/python.md
    - Matplotlib: 
      - matplotlib: Python Fundamentals/matplotlib/plotting.md
  - Molecular Dynamics:
    - Molecular Dynamics/index.md
    - GROMACS:
      - Molecular Dynamics/GROMACS/index.md
      - Set-up:
        - Molecular Dynamics/GROMACS/gmx-ndx.md
      - Analysis:
        - Molecular Dynamics/GROMACS/gmx-rms.md
        - Molecular Dynamics/GROMACS/gmx-gyrate.md
        - Molecular Dynamics/GROMACS/gmx-sasa.md
        - Molecular Dynamics/GROMACS/gmx-eccentricity.md
        - Molecular Dynamics/GROMACS/gmx-dist.md
        - Molecular Dynamics/GROMACS/gmx-gangle.md
        - Molecular Dynamics/GROMACS/gmx-hbond.md
        - Molecular Dynamics/GROMACS/gmx-dssp.md
        - Molecular Dynamics/GROMACS/gmx-cluster.md
        - Molecular Dynamics/GROMACS/gmx-pca.md
  - Documentation Guide:
    - Documentation Guide/contribute.md
    - Documentation Guide/git-contribution-guide.md
    - Configuring Documentation Pages: Documentation Guide/configuring-pages.md
    - Guide to Style and Formatting: Documentation Guide/style-and-formatting.md
